const publications = [
  {
    id: 1,
    title: "Deep Learning for Vision",
    year: 2020,
    conference: "CVPR '20",
  },
  {
    id: 2,
    title: "Graph Neural Networks Explained",
    year: 2021,
    conference: "NeurIPS '21",
  },
  {
    id: 3,
    title: "Advances in NLP with Transformers",
    year: 2022,
    conference: "ACL '22",
  },
  {
    id: 4,
    title: "Federated Learning in Healthcare",
    year: 2023,
    conference: "ICML '23",
  },
  {
    id: 5,
    title: "Self-Supervised Audio Models",
    year: 2019,
    conference: "ICASSP '19",
  },
  {
    id: 6,
    title: "Quantum Computing Applications",
    year: 2024,
    conference: "QCE '24",
  },
  {
    id: 7,
    title: "Robust Reinforcement Learning",
    year: 2020,
    conference: "ICLR '20",
  },
  {
    id: 8,
    title: "3D Reconstruction from Images",
    year: 2021,
    conference: "ECCV '21",
  },
  {
    id: 9,
    title: "Large Scale Language Models",
    year: 2022,
    conference: "EMNLP '22",
  },
  {
    id: 10,
    title: "Generative Adversarial Networks",
    year: 2018,
    conference: "NeurIPS '18",
  },
  {
    id: 11,
    title: "Multi-modal Learning Systems",
    year: 2023,
    conference: "CVPR '23",
  },
  {
    id: 12,
    title: "Explainable AI in Medical Imaging",
    year: 2021,
    conference: "MICCAI '21",
  },
  {
    id: 13,
    title: "Zero-Shot Learning Approaches",
    year: 2020,
    conference: "ECCV '20",
  },
  {
    id: 14,
    title: "Autonomous Navigation Algorithms",
    year: 2019,
    conference: "ICRA '19",
  },
  {
    id: 15,
    title: "Ethics in Artificial Intelligence",
    year: 2024,
    conference: "AAAI '24",
  },
  {
    id: 16,
    title: "Neural Radiance Fields (NeRF)",
    year: 2021,
    conference: "SIGGRAPH '21",
  },
  {
    id: 17,
    title: "Emotion Recognition in Video",
    year: 2022,
    conference: "ICCV '22",
  },
  {
    id: 18,
    title: "Uncertainty Estimation in ML",
    year: 2020,
    conference: "UAI '20",
  },
  {
    id: 19,
    title: "Scaling Laws in Deep Learning",
    year: 2023,
    conference: "NeurIPS '23",
  },
  {
    id: 20,
    title: "Cross-Lingual Speech Models",
    year: 2018,
    conference: "INTERSPEECH '18",
  },
  {
    id: 21,
    title: "Augmented Reality for Education",
    year: 2019,
    conference: "CHI '19",
  },
  {
    id: 22,
    title: "Adversarial Attacks in Vision",
    year: 2022,
    conference: "CVPR '22",
  },
  {
    id: 23,
    title: "Human Pose Estimation",
    year: 2021,
    conference: "ICCV '21",
  },
  {
    id: 24,
    title: "Bias Mitigation in ML Models",
    year: 2023,
    conference: "AAAI '23",
  },
  {
    id: 25,
    title: "Real-time Object Detection",
    year: 2020,
    conference: "ICCV '20",
  },
  {
    id: 26,
    title: "Foundation Models Overview",
    year: 2024,
    conference: "ICLR '24",
  },
  {
    id: 27,
    title: "Personalized Recommendation Systems",
    year: 2022,
    conference: "RecSys '22",
  },
  { id: 28, title: "Low-Power Edge AI", year: 2019, conference: "DATE '19" },
  {
    id: 29,
    title: "Natural Language Generation",
    year: 2018,
    conference: "ACL '18",
  },
  {
    id: 30,
    title: "Machine Learning for IoT Devices",
    year: 2023,
    conference: "SenSys '23",
  },
  {
    id: 31,
    title: "Diffusion Models in Practice",
    year: 2024,
    conference: "CVPR '24",
  },
  {
    id: 32,
    title: "Green AI: Energy-Efficient Learning",
    year: 2024,
    conference: "NeurIPS '24",
  },
  {
    id: 33,
    title: "Vision-Language Models at Scale",
    year: 2024,
    conference: "ICCV '24",
  },
  {
    id: 34,
    title: "Graph Transformers for Molecules",
    year: 2024,
    conference: "ICML '24",
  },
  {
    id: 35,
    title: "Cybersecurity with AI",
    year: 2024,
    conference: "USENIX '24",
  },
  {
    id: 36,
    title: "Interactive AI for Creativity",
    year: 2024,
    conference: "CHI '24",
  },
  {
    id: 37,
    title: "AI for Scientific Discovery",
    year: 2024,
    conference: "AAAI '24",
  },
  {
    id: 38,
    title: "Real-time Language Translation",
    year: 2024,
    conference: "EMNLP '24",
  },
  {
    id: 39,
    title: "Neuro-Symbolic Reasoning Models",
    year: 2024,
    conference: "NeurIPS '24",
  },
  {
    id: 40,
    title: "Ethical Robotics Systems",
    year: 2024,
    conference: "ICRA '24",
  },
  {
    id: 41,
    title: "AI-Powered Drug Discovery",
    year: 2024,
    conference: "ICML '24",
  },
  {
    id: 42,
    title: "Generative Models for Music",
    year: 2024,
    conference: "ISMIR '24",
  },
  {
    id: 43,
    title: "AI in Financial Forecasting",
    year: 2024,
    conference: "KDD '24",
  },
  {
    id: 44,
    title: "Multilingual Speech Recognition",
    year: 2024,
    conference: "ICASSP '24",
  },
  {
    id: 45,
    title: "Interactive 3D Generation",
    year: 2024,
    conference: "SIGGRAPH '24",
  },
  {
    id: 46,
    title: "Learning with Noisy Labels",
    year: 2024,
    conference: "CVPR '24",
  },
  {
    id: 47,
    title: "This is the 20th ",
    year: 2024,
    conference: "ICSE '24",
  },
  {
    id: 48,
    title: "This is 21st",
    year: 2024,
    conference: "CHI '24",
  },
];

export default publications;
